version: '3.8'

services:
  wordpress_db:
    image: mysql:8.0
    container_name: wordpress_db
    restart: always
    ports:
      - "80:80"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password  # Utilisation du fichier secret
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD_FILE: /run/secrets/db_password  # Utilisation du fichier secret
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_root_password
      - db_password

  wordpress:
    depends_on:
      - wordpress_db
    image: wordpress:latest
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress_db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_password
      WORDPRESS_DB_NAME: wordpress
    networks:
      - backend
      - frontend
    volumes:
      - wp_data:/var/www/html
    secrets:
      - db_password

networks:
  frontend:
  backend:

volumes:
  db_data:
  wp_data:

secrets:
  db_password:
    file: ./db_password.txt
  db_root_password:
    file: ./db_root_password.txt
